/**
 *
 * $Id$
 */
package KragsteinPackage.validation;


/**
 * A sample validator interface for {@link KragsteinPackage.Relationship}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RelationshipValidator {
	boolean validate();

	boolean validateTarget(KragsteinPackage.Class value);
	boolean validateSource(KragsteinPackage.Class value);
	boolean validateName(String value);
	boolean validateLowerBound(int value);
	boolean validateUpperBound(int value);
	boolean validateTargetClass(String value);
}
