/**
 *
 * $Id$
 */
package kragstein.validation;

import kragstein.BranchConnection;
import kragstein.Route;

/**
 * A sample validator interface for {@link kragstein.Branch}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BranchValidator {
	boolean validate();

	boolean validateSourceBranchConnection(BranchConnection value);
	boolean validateTargetBranchConnection(BranchConnection value);
	boolean validateRoute(Route value);
	boolean validateName(String value);
}
