/**
 *
 * $Id$
 */
package kragstein.validation;

import kragstein.Attribute;
import kragstein.ClassMultipleRelationships;
import kragstein.Method;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link kragstein.Class}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ClassValidator {
	boolean validate();

	boolean validateTargetConnections(EList<ClassMultipleRelationships> value);
	boolean validateSourceConnections(EList<ClassMultipleRelationships> value);
	boolean validateAttributes(EList<Attribute> value);
	boolean validateMethods(EList<Method> value);
	boolean validateIsSingletone(boolean value);
}
