/**
 *
 * $Id$
 */
package kragstein.validation;

import kragstein.Attribute;
import kragstein.Comment;
import kragstein.Method;
import kragstein.Relationship;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link kragstein.Class}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ClassValidator {
	boolean validate();

	boolean validateAttributes(EList<Attribute> value);
	boolean validateMethods(EList<Method> value);
	boolean validateComments(Comment value);
	boolean validateTargetRelationships(EList<Relationship> value);
	boolean validateSourceRelationships(EList<Relationship> value);
	boolean validateName(String value);
	boolean validateVisibility(String value);
	boolean validateIsSingletone(boolean value);
	boolean validateIsInterface(boolean value);
}
