/**
 *
 * $Id$
 */
package kragstein.validation;

import kragstein.Comment;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link kragstein.CommentLink}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CommentLinkValidator {
	boolean validate();

	boolean validateSourceConnection(EList<Comment> value);
	boolean validateTargetConnection(EList<Comment> value);
	boolean validateSource(Comment value);
	boolean validateTarget(Comment value);
}
