/**
 *
 * $Id$
 */
package kragstein.validation;

import kragstein.IconConnection;
import kragstein.LeftComment;
import kragstein.RightComment;
import kragstein.ValencePoint;

/**
 * A sample validator interface for {@link kragstein.Icon}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface IconValidator {
	boolean validate();

	boolean validateSourceIconConnection(IconConnection value);
	boolean validateTargetIconConnection(IconConnection value);
	boolean validateValencePoint(ValencePoint value);
	boolean validateLeftComment(LeftComment value);
	boolean validateRightComment(RightComment value);
}
