/**
 *
 * $Id$
 */
package kragstein.validation;

import kragstein.Icon;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link kragstein.Route}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RouteValidator {
	boolean validate();

	boolean validateIcons(EList<Icon> value);
}
