/**
 *
 * $Id$
 */
package kragstein.validation;

import kragstein.Unit;
import kragstein.importedPackage;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link kragstein.UMLDiagramm}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface UMLDiagrammValidator {
	boolean validate();

	boolean validateLang(String value);
	boolean validatePackageName(String value);
	boolean validateUnits(EList<Unit> value);
	boolean validatePackages(EList<importedPackage> value);
}
