/**
 *
 * $Id$
 */
package kragstein.validation;

import kragstein.Comment;
import kragstein.Generalization;

/**
 * A sample validator interface for {@link kragstein.Unit}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface UnitValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateSourceConnection(Generalization value);
	boolean validateTargetConnection(Generalization value);
	boolean validateVisibility(String value);
	boolean validateComments(Comment value);
}
