/**
 *
 * $Id$
 */
package KragsteinPackage.validation;

import KragsteinPackage.Attribute;
import KragsteinPackage.ImportedPackage;
import KragsteinPackage.Method;
import KragsteinPackage.Relationship;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link KragsteinPackage.Class}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ClassValidator {
	boolean validate();

	boolean validateAttribute(EList<Attribute> value);
	boolean validateMethod(EList<Method> value);
	boolean validateTargetRelationship(EList<Relationship> value);
	boolean validateSourceRelationship(EList<Relationship> value);
	boolean validateName(String value);
	boolean validateImportedPackage(EList<ImportedPackage> value);
	boolean validateType(String value);
	boolean validateVisibility(String value);
	boolean validateIsSingletone(boolean value);
	boolean validateIsInterface(boolean value);
	boolean validateSuperClass(String value);
	boolean validateSupplierElement(String value);
}
