/**
 *
 * $Id$
 */
package KragsteinPackage.validation;

import KragsteinPackage.Unit;

/**
 * A sample validator interface for {@link KragsteinPackage.Link}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LinkValidator {
	boolean validate();

	boolean validateSource(Unit value);
	boolean validateTarget(Unit value);
	boolean validateTargetClass(String value);
}
