/**
 *
 * $Id$
 */
package KragsteinMethod.validation;

import KragsteinMethod.Branch;

/**
 * A sample validator interface for {@link KragsteinMethod.BranchConnection}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BranchConnectionValidator {
	boolean validate();

	boolean validateSource(Branch value);
	boolean validateTarget(Branch value);
	boolean validateTargetBranch(String value);
}
