/**
 *
 * $Id$
 */
package KragsteinMethod.validation;

import KragsteinMethod.Route;
import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link KragsteinMethod.Question}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface QuestionValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateRoute(Route value);
	boolean validateValue(String value);
	boolean validateYesBelow(boolean value);

	boolean validateRoute(EList<Route> value);
}
